# appveyor.yml

version: 2.0.{build}
image: Visual Studio 2022

install:
  - choco install gitversion.portable -pre -y

before_build:
  - cmd: gitversion /l console /output buildserver /updateAssemblyInfo
  - ps: Update-AppveyorBuild -Version $GitVersion_NuGetVersion
  
  - cmd: dotnet restore src/Seq.App.TelegramAlerts.csproj

build:
  project: src/Seq.App.TelegramAlerts.csproj
  verbosity: minimal

after_build:
  - ps: dotnet pack src/Seq.App.TelegramAlerts.csproj -c Release --no-build -o "$($env:APPVEYOR_BUILD_FOLDER)\bin\nuget" -p:PackageVersion=$env:GitVersion_NuGetVersion

deploy:
  provider: Environment
  name: NuGet_Deployment_Prod
  on:
    branch: main