name: .NET CI/CD (Build & Publish)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/dotnet.yml'
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/dotnet.yml'

env:
  PROJECT_FILE_PATH: src/Seq.App.TelegramNotifier.csproj
  BUILD_CONFIGURATION: Release

jobs:
  build_and_publish:
    runs-on: windows-latest

    steps:
    - name: 1. Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 2. Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 3. Restore Dependencies
      run: dotnet restore ${{ env.PROJECT_FILE_PATH }}

    - name: 4. Build Project
      run: dotnet build ${{ env.PROJECT_FILE_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

    - name: 5. Pack NuGet Package
      id: pack
      run: |
        dotnet pack ${{ env.PROJECT_FILE_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --output nuget_packages

    - name: List NuGet Packages
      run: dir nuget_packages

    - name: 6. Publish to NuGet Gallery
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: dotnet nuget push nuget_packages\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
    
    - name: 7. Publish to GitHub Packages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: dotnet nuget push nuget_packages\*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/ToHoaiBao/index.json" --skip-duplicate
